-- TABLE INFO :
-- SALES – Date, Order_id, Item_id, Customer_id, Quantity, Revenue
-- ITEMS – Item_id, Item_name, price, department
-- CUSTOMERS- customer_id, first_name,last_name,Address

-- Pull total number of orders that were completed on 18th March 2023
SELECT COUNT(Order_id)
    FROM SALES
    WHERE Date="2023-03-18";

-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
SELECT COUNT(Order_id)
    FROM SALES
    WHERE Date="2023-03-18" AND 
    Customer_id IN (
        SELECT Customer_id
            FROM CUSTOMERS
            WHERE First_name="John" AND
                Last_name="Doe"
    );

-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT COUNT(Customer_id), (SUM(Revenue)/COUNT(DISTINCT Customer_id))
    FROM SALES
    WHERE Date LIKE "2023-01-%";

-- Pull the departments that generated less than $600 in 2022
SELECT Department
    FROM ITEMS
    WHERE Item_id IN (
        SELECT Item_id FROM (
            SELECT Item_id, SUM(Revenue) as Rev
            FROM SALES
            WHERE Date LIKE "2022-%"
            GROUP BY Item_id
            HAVING Rev < 600
        )
    );

-- What is the most and least revenue we have generated by an order
SELECT MIN(Rev), MAX(Rev)
    FROM (
        SELECT SUM(Revenue) AS Rev
        FROM SALES
        GROUP BY Order_id
    );

-- What were the orders (items?) that were purchased in our most lucrative order
SELECT Item_name
    FROM ITEMS
    WHERE Item_id=(
        SELECT Item_id FROM (
            SELECT Item_id, MAX(Revenue) FROM SALES
        )
    );